//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class vw_services
{
    public int ServiceKey { get; set; }
    public string ServiceName { get; set; }
    public string ServiceDescription { get; set; }
}

public partial class uspGetGrants_Result
{
    public Nullable<System.DateTime> GrantDate { get; set; }
    public Nullable<decimal> GrantAmount { get; set; }
    public string Servicename { get; set; }
    public Nullable<System.DateTime> GrantDateApproved { get; set; }
}
